language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-22
    - android-24
    - android-28
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

script: ./gradlew connectedAndroidTest
